### ISSUE TITLE
deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by djezlee** [timstallmann/home-assistant-wevolor#3]
Should I be concerned about the features the will remove in a future HA Core version?  Will you provide an update?

**Comment by PTracks** [comment]
> Thx for raising this! I haven't looked into it yet but my assumption is that this should be a pretty easy update, and I'll definitely be releasing a new version addressing this before the deprecation period ends.

Any update on this?  I think the deprecated constants are removed in 2025.1 which is now released.

**Comment by djezlee** [comment]
I have not heard anything, but I look forward to any updates.

**Comment by sabolcik** [comment]
Looks like the integration broke with the 2025.1 core update

**Comment by sabolcik** [comment]
Here is the error log with 2025.1

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 5:36:58 PM (3 occurrences)
Last logged: 9:11:23 PM

Error setting up entry Master Bedroom All Shades for wevolor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wevolor/__init__.py", line 24, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wevolor/cover.py", line 7, in <module>
    from homeassistant.components.cover import (
    ...<8 lines>...
    )
ImportError: cannot import name 'SUPPORT_CLOSE' from 'homeassistant.components.cover' (/usr/src/homeassistant/homeassistant/components/cover/__init__.py)

**Comment by timstallmann** [comment]
Argh I had meant to get this updated over the winter break and did not get around to it. Will try to get a fix up this week!

**Comment by timstallmann** [comment]
https://github.com/timstallmann/home-assistant-wevolor/releases/tag/v1.1.2 is working for me locally on 2024.12 without any deprecation errors but I haven't yet gotten 2025 running on my end to test. @sabolcik or anyone else, can you check if this release fixes the issues you're seeing?

**Comment by djezlee** [comment]
it works on 2025.1...... yaaaas!  Where do I send the coffee?!?
